# Generated by Django 4.2.2 on 2023-08-17 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nails', '0005_schedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='date',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='schedule',
            name='mark',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='schedule',
            name='month',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='schedule',
            name='time',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='schedule',
            name='year',
            field=models.SmallIntegerField(null=True),
        ),
    ]
