# Generated by Django 4.2.2 on 2023-09-10 15:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nails', '0009_remove_services_price_alter_services_title_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserToSpecialization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialization', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='nails.specializations')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='nails.users')),
            ],
        ),
    ]
