# Generated by Django 4.2.2 on 2023-09-16 02:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nails', '0017_alter_usertospecialization_specialization'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServicesToShedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entryShedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nails.schedule')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nails.services')),
            ],
        ),
    ]
