# Generated by Django 4.2.2 on 2023-09-16 04:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nails', '0019_shedulestatus_schedule_service_schedule_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='servicestoshedule',
            old_name='entryShedule',
            new_name='shedule',
        ),
    ]
