# Generated by Django 4.2.2 on 2023-09-16 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nails', '0020_rename_entryshedule_servicestoshedule_shedule'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='mark',
        ),
    ]
